use crate::recurrence::RecurrenceRule;
use crate::DbHandle;
use anyhow::Result;
use chrono::{DateTime, FixedOffset};
use sqlx::FromRow;
use std::collections::HashSet;
use uuid::Uuid;

#[derive(Debug, Clone, FromRow)]
pub struct CalendarEvent {
    pub id: String,
    pub title: String,
    pub description: Option<String>,
    pub location: Option<String>,
    pub start_at: String,
    pub end_at: String,
    pub all_day: i64,
    pub recurrence: Option<String>,
    pub created_at: String,
    pub updated_at: String,
    pub deleted_at: Option<String>,
}

/// Fields for creating a calendar event. Grouped into a struct to keep
/// `insert` within a sane arity and to make call sites self-documenting.
pub struct NewCalendarEvent<'a> {
    pub title: &'a str,
    pub description: Option<&'a str>,
    pub location: Option<&'a str>,
    pub start_at: &'a str,
    pub end_at: &'a str,
    pub all_day: bool,
    pub recurrence: Option<&'a str>,
}

pub async fn insert(db: &DbHandle, event: NewCalendarEvent<'_>) -> Result<CalendarEvent> {
    let id = Uuid::new_v4().to_string();
    let now = chrono::Utc::now().to_rfc3339();
    Ok(sqlx::query_as::<_, CalendarEvent>(
        "INSERT INTO calendar_events
             (id, title, description, location, start_at, end_at, all_day, recurrence,
              created_at, updated_at)
         VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
         RETURNING *",
    )
    .bind(&id)
    .bind(event.title)
    .bind(event.description)
    .bind(event.location)
    .bind(event.start_at)
    .bind(event.end_at)
    .bind(event.all_day as i64)
    .bind(event.recurrence)
    .bind(&now)
    .bind(&now)
    .fetch_one(db.pool())
    .await?)
}

/// Events occurring between `from` and `to` (RFC3339 strings), with `recurrence` EXPANDED
/// across the window — a recurring event surfaces once per in-window occurrence rather than
/// only at its originally-stored `start_at` (phase 13a; previously a recurring event vanished
/// from `upcoming`/the morning brief after its first occurrence). Each returned row keeps the
/// underlying event's `id`; only `start_at`/`end_at` are shifted to that occurrence's own
/// start/end, so `id` stays the stable join key across every occurrence of the same series —
/// what phase 13b's occurrence-vs-series undo scopes on.
///
/// Exception-aware by construction (see `fetch_exceptions`): 13b's occurrence-delete/edit
/// table does not exist yet, so the exception set is always empty here and every expanded
/// occurrence passes through unfiltered.
pub async fn upcoming(db: &DbHandle, from: &str, to: &str) -> Result<Vec<CalendarEvent>> {
    let window_from = DateTime::parse_from_rfc3339(from)
        .map_err(|e| anyhow::anyhow!("calendar::upcoming: invalid 'from' '{from}': {e}"))?;
    let window_to = DateTime::parse_from_rfc3339(to)
        .map_err(|e| anyhow::anyhow!("calendar::upcoming: invalid 'to' '{to}': {e}"))?;

    // A non-recurring event must itself start in-window. A recurring event only needs its
    // stored `start_at` to be at-or-before the window's end — occurrences AFTER `start_at`
    // that land in-window are generated by `expand_event` below, not by this WHERE clause.
    let candidates = sqlx::query_as::<_, CalendarEvent>(
        "SELECT * FROM calendar_events
         WHERE deleted_at IS NULL
           AND (
             (recurrence IS NULL AND start_at >= ? AND start_at <= ?)
             OR (recurrence IS NOT NULL AND start_at <= ?)
           )",
    )
    .bind(from)
    .bind(to)
    .bind(to)
    .fetch_all(db.pool())
    .await?;

    let exceptions = fetch_exceptions();
    let mut occurrences = Vec::new();
    for event in candidates {
        expand_event(event, window_from, window_to, &mut occurrences);
    }
    occurrences.retain(|e| !exceptions.contains(&(e.id.clone(), e.start_at.clone())));
    occurrences.sort_by(|a, b| a.start_at.cmp(&b.start_at));
    Ok(occurrences)
}

/// Exception-subtraction seam for phase 13b: occurrence-level deletes/edits will be recorded
/// as `(event_id, occurrence_start)` pairs in a table 13b adds (its own migration — 13a adds
/// none). That table does not exist yet, so this always returns an empty set and every
/// expanded occurrence in `upcoming` passes through untouched. 13b only needs to replace this
/// body with a real query against its new table — `upcoming`'s expansion/filter shape does
/// not need to change.
fn fetch_exceptions() -> HashSet<(String, String)> {
    HashSet::new()
}

/// Expand one candidate row into its in-window occurrence(s), appending to `out`.
/// Non-recurring rows (and, defensively, rows whose stored `recurrence`/timestamps fail to
/// parse — treated as one-shot rather than dropped, mirroring
/// `recurrence::next_after`'s free-function fallback for a corrupt stored rule) pass through
/// unchanged since the SQL already constrained a non-recurring row's `start_at` to the
/// window. Recurring rows are expanded via `RecurrenceRule::occurrences_in_window`, cloning
/// the base row per occurrence with `start_at`/`end_at` shifted to that occurrence while
/// `id` is left untouched.
fn expand_event(
    event: CalendarEvent,
    window_from: DateTime<FixedOffset>,
    window_to: DateTime<FixedOffset>,
    out: &mut Vec<CalendarEvent>,
) {
    let Some(rule_str) = event.recurrence.as_deref() else {
        out.push(event);
        return;
    };
    let Some(rule) = RecurrenceRule::parse(rule_str) else {
        out.push(event);
        return;
    };
    let (Ok(base_start), Ok(base_end)) = (
        DateTime::parse_from_rfc3339(&event.start_at),
        DateTime::parse_from_rfc3339(&event.end_at),
    ) else {
        out.push(event);
        return;
    };
    let duration = base_end - base_start;

    for start in rule.occurrences_in_window(base_start, window_from, window_to) {
        let mut occurrence = event.clone();
        occurrence.start_at = start.to_rfc3339();
        occurrence.end_at = (start + duration).to_rfc3339();
        out.push(occurrence);
    }
}

pub async fn soft_delete(db: &DbHandle, id: &str) -> Result<bool> {
    let now = chrono::Utc::now().to_rfc3339();
    let rows = sqlx::query(
        "UPDATE calendar_events SET deleted_at = ?, updated_at = ? WHERE id = ? AND deleted_at IS NULL"
    )
    .bind(&now).bind(&now).bind(id)
    .execute(db.pool()).await?.rows_affected();
    Ok(rows > 0)
}

pub async fn get(db: &DbHandle, id: &str) -> Result<Option<CalendarEvent>> {
    Ok(sqlx::query_as::<_, CalendarEvent>(
        "SELECT * FROM calendar_events WHERE id = ? AND deleted_at IS NULL",
    )
    .bind(id)
    .fetch_optional(db.pool())
    .await?)
}
